import { FONT_TYPE } from "@/constant/Constant";


export const FigmaBody = {
  Title_Bold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: "18px",
    paragraph: "0px",
    lineHeight: "24px",
    case: 'original',
  },
  Title: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 500,
    textDecoration: 'none',
    fontSize: "18px",
    paragraph: "0px",
    lineHeight: "24px",
    case: 'original',
  },
  BodyLage: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: "16px",
    paragraph: "0px",
    lineHeight: "28px",
    case: 'original',
  },
  BodyLageBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: "16px",
    paragraph: "0px",
    lineHeight: "28px",
    case: 'original',
  },
  BodyMedium: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: "14px",
    paragraph: "0px",
    lineHeight: "24px",
    case: 'original',
  },
  BodyMediumBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: "14px",
    paragraph: "0px",
    lineHeight: "24px",
    case: 'original',
  },
  BodySmall: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: "12px",
    paragraph: "0px",
    lineHeight: "16px",
    case: 'original',
  },
  BodySmallBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 500,
    textDecoration: 'none',
    fontSize: "12px",
    paragraph: "0px",
    lineHeight: "16px",
    case: 'original',
  },
  BodySmallLight: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 300,
    textDecoration: 'none',
    fontSize: "12px",
    paragraph: "0px",
    lineHeight: "16px",
    case: 'original',
  },
  BodySmallCaption: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: "11px",
    paragraph: "0px",
    lineHeight: "20px",
    case: 'original',
  },
  BodySmallCaptionBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: "0px",
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: "11px",
    paragraph: "0px",
    lineHeight: "20px",
    case: 'original',
  },
};
