import { FONT_TYPE } from "@/constant/Constant";

export const FigmaInput = {
  InputTextMediumBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing:" 0",
    fontWeight: 500,
    textDecoration: 'none',
    fontSize: "14",
    paragraph:" 0",
    lineHeight: "16",
    case: 'original',
  },
  InputTextMedium: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing:" 0",
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: "14",
    paragraph:" 0",
    lineHeight: "16",
    case: 'original',
  },
  InputTextSmall: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing:" 0",
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: "12",
    paragraph:" 0",
    lineHeight: "16",
    case: 'original',
  },
  InputLabelMedium: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing:" 0",
    fontWeight: 500,
    textDecoration: 'none',
    fontSize: "13",
    paragraph:" 0",
    lineHeight: "20",
    case: 'original',
  },
  InputLabelMediumBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing:" 0",
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: "14",
    paragraph:" 0",
    lineHeight: "24",
    case: 'original',
  },
  InputLabelSmall: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing:" 0",
    fontWeight: 500,
    textDecoration: 'none',
    fontSize: "12",
    paragraph:" 0",
    lineHeight: "20",
    case: 'original',
  },
};
