// import "./globals.css";
import ProtectRoute from "@/protect-route/ProtectRoute";
import { Providers } from "@/redux/provider";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ProtectRoute>{children}</ProtectRoute>
          </Providers>
      </body>
    </html>
  );
}
